name: 'Sync to Gist'
description: 'Syncs files to a Gist based on a mapping file or direct content.'
author: 'Simple-Yi'

# 定义 Action 的输入参数
inputs:
  gist_id:
    description: 'The ID of the Gist to sync to'
    required: true
  gist_token:
    description: 'A PAT token with gist scope'
    required: true
  mapping_file:
    description: 'Path to the file that lists which files to sync. Used if mapping_content is not set.'
    required: false
  mapping_content:
    description: 'A multi-line string of mapping rules. Takes precedence over mapping_file.'
    required: false

# 定义 Action 的品牌信息 (在 GitHub Marketplace 中显示)
branding:
  icon: 'git-commit' # Feather Icons 图标名
  color: 'blue'      # 颜色

# 定义 Action 的运行方式
runs:
  using: 'docker'
  image: 'Dockerfile'