name: "Test Action"

on:
  push:
    branches:
      - main
      
  pull_request:

  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出 Action 仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 创建一些用于测试的、内容随机的假文件
      - name: Create dummy files for testing with random content
        run: |
          mkdir -p docs
          echo "This is a guide, generated at $(date +%s%N)." > docs/guide.md
          echo "This is the license, unique ID: $(uuidgen)" > LICENSE

      # 3. 调用本地 Action
      # 使用 `uses: ./` 来指向仓库根目录
      - name: Run Local Action
        uses: ./
        with:
          gist_id: 70da2ca87de98cd7a7ea5dd79a5cb147
          gist_token: ${{ secrets.GIST_TOKEN }}
          mapping_content: |
            docs/guide.md:getting-started.md
            LICENSE