name: "Test Local Action"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出 Action 仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 创建一些用于测试的假文件
      - name: Create dummy files for testing
        run: |
          mkdir -p docs
          echo "This is a guide." > docs/guide.md
          echo "This is the API reference." > docs/api.md
          echo "This is the license." > LICENSE

      # 3. 调用本地 Action
      # 使用 `uses: ./` 来指向仓库根目录
      - name: Run Local Action
        uses: ./
        with:
          gist_id: 70da2ca87de98cd7a7ea5dd79a5cb147
          gist_token: ${{ secrets.GIST_TOKEN }}
          mapping_content: |
            docs/guide.md:getting-started.md
            LICENSE

      # 4. 检查结果 (可选)
      # 克隆 Gist 下来看文件是否存在
      - name: Verify Gist content (optional)
        run: |
          echo "Verification step would go here."
          # git clone https://${{ secrets.GIST_TOKEN }}@gist.github.com/70da2ca87de98cd7a7ea5dd79a5cb147.git test_gist
          # ls -l test_gist
          # grep -q "getting-started.md" <(ls test_gist) && echo "File found!"